### ISSUE TITLE
Bootstrap acceptance tests

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/brute_force_protection#12]
Basic acceptance tests for ensuring the brute-force works as designed

#### Ensuring other users with the same IP can login
- ensure `user1` with `ip1` is blocked after x failed attempts
- ensure `user2` with `ip1` can still login

#### Ensuring that same user with different IP can login
- ensure `user1` with `ip1` is blocked after x failed attempts 
- ensure `user1` with `ip2` is allowed to login

Note - some things we might used during acceptance testing:
`X-Forwarded-For` Header would allow us to set an arbitrary IP in the scenario above

**Comment by phil-davis** [comment]
We might be able to use the ``Ip.php`` core acceptance tests trait that helps firewall to initiate requests from different IP addresses on the local machine. It is likely that there could be 3 addresses always available - drone 172.17.*.*, localhost, and a "real" IP address of the machine. Server on 1 of them and requests can come in from the others.

**Comment by individual-it** [comment]
this is not fixed yet completely, reopening

**Comment by individual-it** [comment]
tried with `Ip.php` but as we run the tests on a remote system in drone we only have one IP address that we can use. Will think about use of `X-Forwarded-For`
