### ISSUE TITLE
brute_force_protection 1.1.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/brute_force_protection#129]
needs release at least because of issue #57 PR #90 (which also depends on core 10.5.0)
And minor fix to docs link from PR #130 

## QA Issues found
* [x] #134 
* [x] incomplete translations

**Comment by phil-davis** [comment]
Ref: discussion in issue #85

**Comment by karakayasemi** [comment]
- documentation path update https://github.com/owncloud/brute_force_protection/pull/130

**Comment by HanaGemela** [comment]
### Product approval

- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier

### QA

- [ ] Generate Changelog
- [ ] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [ ] Bump version in `info.xml` (no version suffix)
- [ ] Check php version dependency in `info.xml`
- [ ] Check minimum ownCloud version dependency in `info.xml`
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Create github tag for `v${version}RC1` on release branch
- [ ] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [ ] Rename last RC tarball to final
- [ ] Create github tag for final `v${version}` on release branch
- [ ] Upload as Github release using changelog entries

### Publishing

- [ ] Upload tarball to marketplace (see handbook for details)
- [ ] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
Tag has been created https://github.com/owncloud/brute_force_protection/releases/tag/v1.1.0RC1 but signing doesn't work

**Comment by karakayasemi** [comment]
@HanaGemela This app initially developed by me as a community app. I can create a signed tarball for the QA team or hand over the key if you prefer.

**Comment by HanaGemela** [comment]
@davitol RC1 for testing https://github.com/owncloud/brute_force_protection/releases/tag/v1.1.0RC1

**Comment by davitol** [comment]
> @davitol RC1 for testing https://github.com/owncloud/brute_force_protection/releases/tag/v1.1.0RC1

There is no Changelog file included in the tarball

**Comment by phil-davis** [comment]
PR #131 will get the changelog into the tarball.

**Comment by HanaGemela** [comment]
@karakayasemi could you please create a new signed RC2 tarball?

**Comment by karakayasemi** [comment]
RC2 release has been created in here: https://github.com/owncloud/brute_force_protection/releases/tag/v1.1.0RC2

**Comment by davitol** [comment]
>     * Verify transifex commits are in master: If a folder https://github.com/owncloud//tree/master/l10n exists, then https://drone.owncloud.com/owncloud/ should receive nightly '[tx] updated from transifex` ...

There are missing strings for Deutsch (Persönlich), Förmlich LGTM @pmaier1 
<img width="308" alt="Screenshot 2020-09-07 at 09 17 36" src="https://user-images.githubusercontent.com/10596560/92359206-2eb7ce00-f0eb-11ea-881b-41adc01c7a8a.png">

Also arabics is missed:

<img width="315" alt="Screenshot 2020-09-07 at 09 23 54" src="https://user-images.githubusercontent.com/10596560/92359627-e0ef9580-f0eb-11ea-9118-e0f2d54bd51b.png">

**Comment by pmaier1** [comment]
> There are missing strings for Deutsch (Persönlich), Förmlich LGTM @pmaier1

> Also arabics is missed:

Transifex shows 100% for German and Arabic. Issue with sync job, I guess.

**Comment by davitol** [comment]
Reopened: https://github.com/owncloud/brute_force_protection/issues/31#issuecomment-688179553

**Comment by jnweiger** [comment]
Last update in Transifex was June 13, 2020
Is that correct?

**Comment by pmaier1** [comment]
Last source update: Aug 7th 2020, 03:47

**Comment by davitol** [comment]
<img width="789" alt="Screenshot 2020-09-07 at 12 57 10" src="https://user-images.githubusercontent.com/10596560/92388775-1ca05480-f118-11ea-82e9-21e2c0330d58.png">
String messages are not translated even in Förmlich German (Transifex contains the right string translated but it does not get translated using the app)

**Comment by davitol** [comment]
IMHO a possible blocker @karakayasemi @pmaier1 https://github.com/owncloud/brute_force_protection/issues/134

**Comment by jnweiger** [comment]
@karakayasemi I have tagged 1.1.0RC3 -- can you please build the tarball for our QA? thanks!

**Comment by karakayasemi** [comment]
I created a new tarball 1.1.0RC3 and published with 1.1.0RC3. Thank you for your help.

**Comment by davitol** [comment]
> I created a new tarball and published with 1.1.0RC3. Thank you for your help.

Tested with Tarball located in https://github.com/owncloud/brute_force_protection/releases/download/v1.1.0RC3/brute_force_protection.tar.gz and LGTM

@jnweiger Please :shipit:

**Comment by jnweiger** [comment]
@karakayasemi 1.1.0 passed QA, you can now proceed with the upload to https://marketplace.owncloud.com/apps/brute_force_protection

**Comment by karakayasemi** [comment]
https://marketplace.owncloud.com/apps/brute_force_protection v1.1.0 has been released. 🎉

**Comment by karakayasemi** [comment]
@jnweiger is there anything left to be done for closing this ticket?

**Comment by jnweiger** [comment]
Mailings done, release checklist complete. final close.
