### ISSUE TITLE
occ command to set values

### ISSUE THREAD

**Issue by mmattel** [owncloud/brute_force_protection#16]
@karakayasemi 

It would be good to have the ability to configure the parameters also via occ command.
The key names could be like:
- ``bfp:get``
- ``bfp:set``

The arguments could be like:
- ``--time_threshold``
- ``--ban_period``
- ``--fail_tolerance``

The options for get could be like:
- ``--all`` or an argument

Pls see also:
https://github.com/owncloud/documentation/issues/4379 (brute_force_protection: settings/admin)
https://github.com/owncloud/documentation/pull/4381 (Splitting occ_command.rst into two files for core and apps)

**Comment by DeepDiver1975** [comment]
App config values can already be Set via occ. Brute firce protection Just uses app config.
Documenting this properly shall be enough.

 $this->config->getAppValue(
			'brute_force_protection',
			'brute_force_protection_fail_tolerance',
			'3'
		);

**Comment by karakayasemi** [comment]
@mmattel , as @DeepDiver1975 said, all config values already can be configured via occ command. https://doc.owncloud.org/server/latest/admin_manual/configuration/server/occ_command.html#config-commands. 
But, we should document this on documentation and this repository's README file. If everyone agrees, we can close this ticket and follow this topic on the other documentation related issues:  #4. #5

**Comment by mmattel** [comment]
Did not know.
Closing is fine.
I have already created an occ command file for apps (see above).
I will add a note there

**Comment by mmattel** [comment]
Added a description in owncloud/documentation#4381
