### ISSUE TITLE
App counts wrong for failed logins and public shares with password

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/brute_force_protection#197]
If in the settings under "Ban after how many failed attempts?" 3 attempts are set, it will only be banned after the 4th wrong attempt. This is the same for logins as for public shares with a password

This can be fixed with pull request #196 and #198

**Comment by jnweiger** [comment]
No. the count is correct.
After three wrong paswords,  the user is blocked. But, the message 
![grafik](https://user-images.githubusercontent.com/1108546/225308349-6c042895-4353-4ebe-ad05-e7ec3daf6de4.png)
is not yet shown.
This message is only shown on the next login attempt. Regardless if done with wrong or correct password.
