### ISSUE TITLE
[QA] login is blocked after enting correct password

### ISSUE THREAD

**Issue by jnweiger** [owncloud/brute_force_protection#199]
Seen with brute_force_protection 1.1.0 and docker compose setup as per https://doc.owncloud.com/server/10.12/admin_manual/installation/docker/#docker-compose

* enable app, keep settings per default (3 fail attempts), but reduce locked time for easier testing... 
* try log in as admin with a wrong password 5 times. The app does not trigger. BAD
* log in a sixth time, now with correct password. The app triggers and blocks the user.  BAD.

Seen by @voroyam

**Comment by GeraldLeikam** [comment]
reproducible with version 1.1.0 -> fixed in version 1.2.0
