### ISSUE TITLE
php-cs-fixer

### ISSUE THREAD

**Issue by mmattel** [owncloud/brute_force_protection#3]
@DeepDiver1975, @PVince81, @karakayasemi   
Any plans to implement php-cs-fixer (in an early stage) as we have in core and the other repros ?

**Comment by karakayasemi** [comment]
Let me look for it, we can add to the current pull request. #1

**Comment by mmattel** [comment]
@karakayasemi any update on this?

**Comment by karakayasemi** [comment]
@mmattel see #11, I could not find clear documentation about php-cs-fixer. I tried to make something similar with other repos php-cs-fixer pull request.
