### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by mmattel** [owncloud/brute_force_protection#31]
It would be great to have a meaningful app icon that is shown in the settings/general/apps page.
Else the standard image is shown 
![image](https://user-images.githubusercontent.com/3321281/45489581-eb792d80-b764-11e8-939c-2eb900f9fb91.png)
which is not really expressive.

@hurradieweltgehtunter

**Comment by hurradieweltgehtunter** [comment]
I'll add this to our Todo list for upcoming app releases.
Thanks for this idea!

**Comment by mmattel** [comment]
closed by #61

**Comment by davitol** [comment]
Tested with tarball located in https://github.com/owncloud/brute_force_protection/releases/download/v1.1.0RC2/brute_force_protection.tar.gz and the App icon is not shown

<img width="373" alt="Screenshot 2020-09-07 at 10 59 42" src="https://user-images.githubusercontent.com/10596560/92369385-3f6f4080-f0f9-11ea-9c84-0f6913dd0d70.png">

**Comment by jnweiger** [comment]
The icon in img/app.svg was 800kb in size and contained 4 drop shadows made with inline PNG. @hurradieweltgehtunter  could that be a problem? 
Find attached a version of the same icon without these shadows. 4kb. 
[app.svg.zip](https://github.com/owncloud/brute_force_protection/files/5182666/app.svg.zip)

**Comment by hurradieweltgehtunter** [comment]
Fine with me. 800kb is way too much :) 👍

**Comment by karakayasemi** [comment]
There was a problem on packaging. Resolved with #133

**Comment by davitol** [comment]
Icon now is shown. JFYI, the rest of the app icons are shown in grey but Brute Force Protection icon is beautifully colored.

<img width="963" alt="Screenshot 2020-09-21 at 14 08 17" src="https://user-images.githubusercontent.com/10596560/93846954-d9acb800-fca5-11ea-8430-0756011bb660.png">

**Comment by hurradieweltgehtunter** [comment]
The idea was to create new coloured app icons but mgmt said no. Brute Force Protection was the first app we created the icon before it was stopped.
