### ISSUE TITLE
calling `status.php` resets the timer

### ISSUE THREAD

**Issue by individual-it** [owncloud/brute_force_protection#32]
1. set threshold-time=30 fail-tolerance=2 ban-period=3000
1. create a user `user0` and password `1111`
1. run 3x `curl -uuser0:111 -X PROPFIND http://localhost/owncloud-10.0.10/RC3/remote.php/webdav/`
    - expected message `Too many failed login attempts. Try again in 50 minutes.` :heavy_check_mark: 
1. `curl  http://localhost/owncloud-10.0.10/RC3/status.php`
1. `curl -uuser0:1111 -X PROPFIND http://localhost/owncloud-10.0.10/RC3/remote.php/webdav/`
   - block message is expected
   - PROPFIND result is returned

**Comment by karakayasemi** [comment]
I guess we can close this, probably it is about threshold time. IMHO, calling status.php cant affect it. The decision algorithm for banning an IP is in this function: https://github.com/owncloud/brute_force_protection/blob/master/lib/Throttle.php#L95 .  Let's continue to discuss in #33 .
