### ISSUE TITLE
Documentation of App "Brute Force Protection" 

### ISSUE THREAD

**Issue by mmattel** [owncloud/brute_force_protection#5]
The capability of this app needs documentation preperation, as earlier as better, makes things more easy and relaxed when app is ready/available.

https://github.com/owncloud/documentation/issues/4334

@voroyam @settermjd

**Comment by karakayasemi** [comment]
https://github.com/owncloud/docs/issues/262 already merged, @mmattel let's close this one also?

**Comment by mmattel** [comment]
Yes we can close this issue.
Doc implemented, see: https://doc.owncloud.com/server/admin_manual/configuration/server/app_commands/brute_force_protection_commands.html

@karakayasemi please take a look on the linked page and check if there is something to add because of merged PR 90 in BFP. In case, create a new issue and reference to BPF#90.

**Comment by karakayasemi** [comment]
Another documentation is here https://doc.owncloud.com/server/latest/admin_manual/configuration/server/security/brute_force_protection.html . 

The application config parameters still the same and they now apply to both login and share link protection. We may want to mention in docs that public link passwords are also under protection now.

**Comment by mmattel** [comment]
> We may want to mention in docs that public link passwords are also under protection now

👍 pls add an issue and if possible a reference to the page where to be added

**Comment by karakayasemi** [comment]
Related documentation issue: https://github.com/owncloud/docs/issues/2682
