### ISSUE TITLE
core 10.3 is out - make new BF release available ?

### ISSUE THREAD

**Issue by mmattel** [owncloud/brute_force_protection#85]
What is the plan for a new BFP release on the marketplace?
Initial release was Dec. 2018, no update was done since

@karakayasemi

**Comment by karakayasemi** [comment]
@mmattel There is no significant change on the app, also it is still compatible with 10.3. I would like to create a new release with this feature: https://github.com/owncloud/brute_force_protection/issues/57 . 

If we agree on protected public links blocking policy, we can implement the feature and create a new release with it.

**Comment by mmattel** [comment]
You typed faster than I did, was just on the way adding it to the wishlist :smile:

**Comment by mmattel** [comment]
@karakayasemi now pr #90 is merged, a new release can be created :smile:

**Comment by karakayasemi** [comment]
We need to wait for server version 10.5 now 😃 
https://github.com/owncloud/brute_force_protection/blob/5f83f8f7995e3f7a6fe3ae88ba7ccc23f6954481/appinfo/info.xml#L28

**Comment by phil-davis** [comment]
I created issue #129 and put it in the Releases project, so it will be seen in the list of apps to release with core 10.5.0.
